// <auto-generated />
using HotelCRM.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HotelCRM.Migrations
{
    [DbContext(typeof(HotelCRMContext))]
    [Migration("20210107000923_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HotelCRM.Models.Guest", b =>
                {
                    b.Property<int>("GuestId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("Hometown");

                    b.Property<int>("LifetimeNights");

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.Property<int>("PropertyId");

                    b.Property<int>("RoomId");

                    b.Property<string>("VIPTier");

                    b.HasKey("GuestId");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("HotelCRM.Models.GuestProperty", b =>
                {
                    b.Property<int>("GuestPropertyId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("GuestId");

                    b.Property<int>("PropertyId");

                    b.HasKey("GuestPropertyId");

                    b.HasIndex("GuestId");

                    b.HasIndex("PropertyId");

                    b.ToTable("GuestProperty");
                });

            modelBuilder.Entity("HotelCRM.Models.GuestRoom", b =>
                {
                    b.Property<int>("GuestRoomId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("GuestId");

                    b.Property<int>("RoomId");

                    b.HasKey("GuestRoomId");

                    b.HasIndex("GuestId");

                    b.HasIndex("RoomId");

                    b.ToTable("GuestRoom");
                });

            modelBuilder.Entity("HotelCRM.Models.Property", b =>
                {
                    b.Property<int>("PropertyId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Name");

                    b.Property<string>("Neighborhood");

                    b.Property<int>("Stars");

                    b.HasKey("PropertyId");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("HotelCRM.Models.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("MaxOccupancy");

                    b.Property<int>("PropertyId");

                    b.Property<int>("RoomNumber");

                    b.Property<string>("RoomType");

                    b.HasKey("RoomId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("HotelCRM.Models.GuestProperty", b =>
                {
                    b.HasOne("HotelCRM.Models.Guest", "Guest")
                        .WithMany("Properties")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HotelCRM.Models.Property", "Property")
                        .WithMany("Guests")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HotelCRM.Models.GuestRoom", b =>
                {
                    b.HasOne("HotelCRM.Models.Guest", "Guest")
                        .WithMany("Rooms")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HotelCRM.Models.Room", "Room")
                        .WithMany("Guests")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
